### ISSUE TITLE
2.2.0 ~ 2.3.1 hincrby issue

### ISSUE THREAD

**Issue by nick8081** [alisaifee/coredis#138]
async def hincrby(self, key, field, amount=1):
        """Increments the value of ``field`` in hash ``key`` by ``amount``"""

        return await self.execute_command("HINCRBY", key, key, amount)

in execute_command invocation, the second argument "key" should be "field".

**Comment by alisaifee** [comment]
Hi @nick8081 yes I see that that bug existed in the 2.x series where the code was mostly aredis with some small cleanups to be python 3.10 compliant. This was fixed in the first round of refactoring (3.x) in #20 which means both the 3.x and the 4.x (current) versions don't have this issue. Is there a reason you're using 2.x?

**Comment by nick8081** [comment]
It is history reason, our project is using aredis.

**Comment by alisaifee** [comment]
Okay, I'll try to do a release for 2.x to address that one issue (there are probably others as well though, and I'd strongly recommend you try to upgrade to 4.x)

**Comment by alisaifee** [comment]
I've made a [2.3.2](https://pypi.org/project/coredis/2.3.2/) release which contains the fix.
