### ISSUE TITLE
OpenTelemetry Integration

### ISSUE THREAD

**Issue by roma-glushko** [alisaifee/coredis#158]
It would interesting to see `coredis` integrated with OpenTelemetry. 

At the moment, OpenTelemetry has only the integration with the official redis library:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/__init__.py

Getting coredis on the board could aid further adoption of this great library in the community. 

When it comes to the implementation, I may be able to help here.

**Comment by alisaifee** [comment]
This has been on my list for a while, and I would love to see this in the library! 

I personally don't have much experience with otel but I wonder if it's possible to implement the integration in coredis itself instead of by monkey patching?

**Comment by alisaifee** [comment]
> Yes, it's absolutely possible to make this without monkey patching.

That would be my preference! There's a lot of "implementation detail" in the internals of coredis and I feel some interesting metrics would be lost if the instrumentation was monkey patched (one example that comes to mind is if you enable [client side caching](https://coredis.readthedocs.io/en/latest/handbook/caching.html#tracking-cache) - it would be nice to see the stats around that, and it would be much easier to implement that internally).

>  But the question here: would that be okay to keep it there and ship to all users (even those who elected to use non-OTel-based observation stacks)?

I think this is fine as long as it's not a hard requirement for installation. We could provide an install extra so that users could do for example `pip install coredis[otel]` and automatically get the dependency that is tested against and the part of the code that enables instrumentation could silently be disabled when the dependency is not available. Something like this already exists for runtime type checking via [beartype](github.com/beartype/beartype) - [here](https://github.com/alisaifee/coredis/blob/master/coredis/typing.py#L80).

**Comment by alisaifee** [comment]
@roma-glushko I'll close this for now since it's not actually an issue, but if you'd like please start a discussion
