### ISSUE TITLE
Delete function does not work

### ISSUE THREAD

**Issue by JohnnyRacer** [alisaifee/coredis#69]
```
async def redis_test():
    await pol_limit.rdb.set('abc', 'fgh')
    res = await pol_limit.rdb.get('abc')
    print(res)
    await pol_limit.rdb.delete('abc')
    res = await pol_limit.rdb.get('abc')
    print(res)
```

Running this function with asyncio.run I am always getting the value I've set instead of nothing, the delete function itself returns a 0 instead of 1 when using the regular `redis` package from PyPi. Any help is much appreciated.

**Comment by alisaifee** [comment]
This is because the `delete` method expects a collection of keys not variable positional arguments. The coredis API does not follow the regular redis API as of version `3.x` and specifically diverges for commands that accept one or more keys as arguments ([reference](https://coredis.readthedocs.io/en/stable/history.html)). 

I would strongly recommend using type checking with coredis as all the redis commands are well typed.  You can also enable runtime type checking in development or testing if the rest of your code doesn't have type annotations ([details](https://coredis.readthedocs.io/en/stable/handbook/typing.html)).

For example:
Install beartype and coredis
```bash
pip install coredis beartype
```

Run the following snippet and you'll see the type error
```bash
COREDIS_RUNTIME_CHECKS=1 python -c 'import coredis
import asyncio
asyncio.run(coredis.Redis().delete("fubar"))
'
```

Versus:

```bash
COREDIS_RUNTIME_CHECKS=1 python -c 'import coredis
import asyncio
asyncio.run(coredis.Redis().delete(["fubar"]))
```

**Comment by alisaifee** [comment]
Great!

Regarding type checking - the environment variable basically turns on runtime type checking if the [beartype](https://github.com/beartype/beartype) library is available. This is mostly done because there is a small performance impact of having the feature enabled.

You can of course still use static type checking on your code with mypy or pyright and in fact those would have caught the issue as well.
