### ISSUE TITLE
Locking capability?

### ISSUE THREAD

**Issue by coandco** [alisaifee/coredis#71]
It looks like locking capability no longer exists in coredis.  Why is that?

**Comment by alisaifee** [comment]
The motivation behind removing the lock implementations was to align & focus the features of the library to providing interfaces to native redis operations. 

The lock [implementation](https://github.com/alisaifee/coredis/blob/3.x/coredis/lock.py) that existed is more of an application component that imho should be either in the upstream using coredis or in a separate library (especially since the preferred one is mostly written in LUA). I'm considering adding a **recipes** section to the documentation where something like this would make sense - though I have to cleanup/update the code as it is still in the same state it was when coredis was forked from aredis.

**Comment by coandco** [comment]
Ahh, fair enough.  I just found coredis and was hoping I could move to it, since it's one of the few featureful/maintained async redis cluster implementations that I've come across.  It'll be a harder sell if I have to implement a locking algorithm myself, though.  Thanks for your work on this!

**Comment by alisaifee** [comment]
@coandco I've pushed a version of the lock described by [the redis reference for distributed locks](https://redis.io/docs/reference/patterns/distributed-locks/#correct-implementation-with-a-single-instance) in #72. 

This is mostly what existed in aredis and coredis versions < 4 (and in fact very similar to what you might find in [async redis-py](https://github.com/redis/redis-py/blob/master/redis/asyncio/lock.py), [regular redis-py](https://github.com/redis/redis-py/blob/master/redis/lock.py) etc...) - however, re-written to use some of the newer features in coredis. Note that there is no longer two different classes for single node and cluster. Also, instead of explicitly checking the replicas to see if the lock had percolated, the implementation uses the `WAIT` command to ensure that the lock was acquired and replicated to atleast 1 replica.

**Comment by coandco** [comment]
Thanks!  Surprisingly, the official async redis-py ClusterRedis client doesn't have a lock implementation, which is why I went hunting for aredis (and eventually coredis).  I'll look forward to trying out the new coredis lock when it gets released to PyPI -- thank you so much for the quick turnaround!

**Comment by alisaifee** [comment]
Support for locks both with standalone instance and cluster has been re-introduced under `coredis.recipes.locks` (`LuaLock`) in [4.1.0](https://github.com/alisaifee/coredis/releases/tag/4.1.0).
Details in [documentation](https://coredis.readthedocs.io/en/latest/recipes/locks.html#distributed-lock-with-lua-scripts)

**Comment by coandco** [comment]
Looks like the .lua files didn't make it into the PyPI package:

```
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.local/lib/python3.9/site-packages/coredis/recipes/locks/extend.lua'
$ ls -l ~/.local/lib/python3.9/site-packages/coredis/recipes/locks/
total 20
-rw-rw-r-- 1 clint clint   89 Jul 18 21:11 __init__.py
-rw-rw-r-- 1 clint clint 8309 Jul 18 21:11 lua_lock.py
drwxrwxr-x 2 clint clint 4096 Jul 18 21:11 __pycache__
```

**Comment by alisaifee** [comment]
ouch! I had tried to catch that error midway during tagging/building and looks like I messed it up cause I got distracted by dinner :facepalm:

Sorry about that, this should be addressed by 3efe764  and in [4.1.1](https://github.com/alisaifee/coredis/releases/tag/4.1.1)

**Comment by alisaifee** [comment]
@coandco I'll leave this open and let you close this if it satisfies at least a minimum requirement for your use case.

**Comment by alisaifee** [comment]
Minor note, there was a bug in the implementation of `ensure_replication` where if you have more than 1 replica per shard there is an error. This will be addressed in `4.2.1` shortly.

**Comment by coandco** [comment]
Finally getting around to testing this, apologies for the delay.  Here's what I've found:
1) In my non-prod local-testing Redis Cluster setup, I don't have any replicas set up, just three masters.  In that mode, this recipe blocks forever because of the line `with self.client.ensure_replication(1, timeout_ms=0):`, which says "wait until it's written to at least one replica and block forever until it is".
2) For setups with more than 1 replica per shard, other cluster-locking mechanisms I've seen wait until it's been written to at least half of the replicas assigned to the hash slot.  It seems to me that this would fix both problems -- just ensure_replication to `math.ceil(num_replicas_for_slot/2)` replicas.  That way, if there are zero replicas, it won't block forever, and if there are (say) 3 replicas per primary it would block until 2 of the 3 have been written to.

Of course, I'm mostly spitballing here -- it sounds like you know how this works much more completely than I do.  Does the above sound reasonable?

**Comment by alisaifee** [comment]
Thanks for testing it out!
Your idea is what I should have done (and is infact pretty much what the previous implementation did - just explicitly instead of using WAIT) I got lazy and hard coded 1. 

I'll try to put up something along those lines shortly!

Also, I didn't actually know you could run a cluster with 0 replicas - thanks! - I'm going to add that to the test suite as well since I've never actually tested that for other cluster related functionality!

**Comment by coandco** [comment]
Yup!  Running a cluster without replicas isn't something you'd want to do in prod, certainly, as it somewhat defeats the purpose when it comes to high availability, but it's a close enough approximation in a local testing environment.

**Comment by alisaifee** [comment]
@coandco if you get a chance, please take a look at #86 which contains details of the changes/improvements to the cluster lock. I'll shortly make a dot release with them.

**Comment by coandco** [comment]
I've done some preliminary testing of my code with what's in master, and it looks good so far.  Looking forward to the dot release so I can test end to end.

**Comment by alisaifee** [comment]
Apologies for the delay. [4.5.1](https://github.com/alisaifee/coredis/releases/tag/4.5.1) is being built and should be on pypi soon.

**Comment by alisaifee** [comment]
@coandco mind if I close this off now?

**Comment by coandco** [comment]
Oh, sorry, thought I had already closed it.  Close away!

**Comment by alisaifee** [comment]
:bow: lock away!
