### ISSUE TITLE
Why not Python 3.7？

### ISSUE THREAD

**Issue by sunhailin-Leo** [alisaifee/coredis#79]

**Comment by alisaifee** [comment]
Initially when coredis was forked from aredis it was dropped to simplify porting to support 3.10+ (it wasn't necessary, just made things a bit easier).
At the moment syntactically 3.7 won't work because of extensive use of the walrus operator.

**Comment by sunhailin-Leo** [comment]
> Initially when coredis was forked from aredis it was dropped to simplify porting to support 3.10+ (it wasn't necessary, just made things a bit easier).
> At the moment syntactically 3.7 won't work because of extensive use of the walrus operator.

If I remove all walrus operator. How can i build on Python3.7?

**Comment by sunhailin-Leo** [comment]
In my opinion, I think third-party libraries should remain compatible with Python 3.7 or 3.6 at a minimum until Python 3.11 is released.

**Comment by alisaifee** [comment]
3.6 is already EOL.

To clarify - I don't have any opposition to python 3.7 compatibility I just didn't have a use case for it.

If there is a justification for re-introducing it without making the code difficult to reason with, I'm happy to take a pull request.

**Comment by sunhailin-Leo** [comment]
> 3.6 is already EOL.
> 
> To clarify - I don't have any opposition to python 3.7 compatibility I just didn't have a use case for it.
> 
> If there is a justification for re-introducing it without making the code difficult to reason with, I'm happy to take a pull request.

In my opinion, it is much easier to upgrade a production project's dependencies than to upgrade a Python version. Since Python 3.8 to Python 3.10 offers fewer performance optimizations for production, it is preferable to upgrade dependencies rather than Python versions as a production project.

**Comment by alisaifee** [comment]
> In my opinion, it is much easier to upgrade a production project's dependencies than to upgrade a Python version. 

I'm not sure I understand the above as `coredis` has never supported python 3.7.

Is it:
1) Your production project was using an older version of coredis that accidentally worked with python 3.7 and now updating the dependency to the latest 4.x versions doesn't work?
**or**
2) You are introducing it into a python 3.7 project and it doesn't work since it doesn't support python 3.7

**Comment by sunhailin-Leo** [comment]
I using `coredis` 2.3.1 on my production project now. But I found I can not install `coredis` latest version on my local environment.（MacOS，Python 3.7）

**Comment by alisaifee** [comment]
> I using `coredis` 2.3.1 on my production project now.

This makes sense now. Also, my apologies - I was wrong about `coredis` never having supporting 3.7 since the 2.x series was meant to be backward compatible with `aredis` and that compatibility was only broken in 3.x (Where python 3.7 was dropped).

I'll take a look at the feasibility of re-introducing 3.7

**Comment by alisaifee** [comment]
Python 3.7 support has been brought back in [4.5.0](https://github.com/alisaifee/coredis/releases/tag/4.4.0).
